apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nwtool
    test: test
  name: network-multitool-250
  namespace: dev
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: Always
    name: nwtool
