apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nwtool
  name: network-multitool-605
  namespace: dev
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: Always
    name: nwtool